DROP DATABASE IF EXISTS ingredientsDb;
CREATE DATABASE ingredientsDb;

USE ingredientsDb;

CREATE TABLE meals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  ingredients VARCHAR(10000) NOT NULL,
  category VARCHAR(50),
  area VARCHAR(50),
  howTo TEXT NOT NULL,
  imageURL VARCHAR(500),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE drinks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  category VARCHAR(10000) NOT NULL,
  alcoholic VARCHAR(50),
  instructions VARCHAR(50),
  ingredients TEXT NOT NULL,
  measurements VARCHAR(500),
  image VARCHAR(500),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


